services:
  dns-server:
    image: andyshinn/dnsmasq:2.78
    container_name: dns-server
    command:
      - "-k"
      - "--log-facility=-"
      - "-C"
      - "/etc/dnsmasq.conf"
    cap_add:
      - NET_RAW
      - NET_ADMIN
    volumes:
      - ./dnsmasq.conf:/etc/dnsmasq.conf:ro
    networks:
      forensic-net:
        ipv4_address: 192.168.10.40
    ports:
      - "53:53/udp"
      - "53:53/tcp"
    restart: unless-stopped

networks:
  forensic-net:
    ipam:
      config:
        - subnet: 192.168.10.0/24
